// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADfFR40p_vr4wbNFrps8tUVthwgxWlCY0',
    appId: '1:592127344190:web:7581a8ef2892aee19a5b6f',
    messagingSenderId: '592127344190',
    projectId: 'my-awesome-project-01-c4e3e',
    authDomain: 'my-awesome-project-01-c4e3e.firebaseapp.com',
    storageBucket: 'my-awesome-project-01-c4e3e.firebasestorage.app',
    measurementId: 'G-YF09JNYMYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUfhgP_raemmCxaoSMcb5A1U3DXVHsJ34',
    appId: '1:592127344190:android:c828885bc3ac4ade9a5b6f',
    messagingSenderId: '592127344190',
    projectId: 'my-awesome-project-01-c4e3e',
    storageBucket: 'my-awesome-project-01-c4e3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6-zjgeUtGzBT9OfRCZKzCNpSnZVLY7qY',
    appId: '1:592127344190:ios:93657abb9e2051a09a5b6f',
    messagingSenderId: '592127344190',
    projectId: 'my-awesome-project-01-c4e3e',
    storageBucket: 'my-awesome-project-01-c4e3e.firebasestorage.app',
    iosBundleId: 'com.example.tenantClientFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6-zjgeUtGzBT9OfRCZKzCNpSnZVLY7qY',
    appId: '1:592127344190:ios:93657abb9e2051a09a5b6f',
    messagingSenderId: '592127344190',
    projectId: 'my-awesome-project-01-c4e3e',
    storageBucket: 'my-awesome-project-01-c4e3e.firebasestorage.app',
    iosBundleId: 'com.example.tenantClientFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADfFR40p_vr4wbNFrps8tUVthwgxWlCY0',
    appId: '1:592127344190:web:1d84f43c63505a089a5b6f',
    messagingSenderId: '592127344190',
    projectId: 'my-awesome-project-01-c4e3e',
    authDomain: 'my-awesome-project-01-c4e3e.firebaseapp.com',
    storageBucket: 'my-awesome-project-01-c4e3e.firebasestorage.app',
    measurementId: 'G-HM03YWFBGN',
  );
}
